export {
  APP_NAME,
  APP_VERSION,
  DEFAULT_SUPPORTED_EXTENSIONS,
  SEARCH_LIMIT_DEFAULT,
  SEARCH_LIMIT_MAX,
  RESOURCE_LIST_LIMIT,
  SCAN_WARNING_LIMIT,
  FINGERPRINT_WINDOW_BYTES,
  DEFAULT_TARGET_DURATION_MS,
  DEFAULT_TRANSITION_OVERLAP_MS,
  SHORT_CROSSFADE_MS,
  MIN_PLAYABLE_DURATION_MS,
  DURATION_TOLERANCE_MS,
  DEFAULT_ARTIST_REPEAT_SPACING,
  MAX_BPM_JUMP,
  MAX_CAMELOT_DISTANCE_OK,
  MAX_ENERGY_DEVIATION,
  SET_PLAN_LIST_LIMIT_MAX,
  COMPATIBLE_TRACKS_LIMIT_MAX,
  PLANNER_CANDIDATE_CAP,
  DEFAULT_SCORE_WEIGHTS,
  DEFAULT_LOUDNESS_TARGET_LUFS,
  DEFAULT_TRUE_PEAK_CEILING_DB,
  DEFAULT_RENDER_SAMPLE_RATE_HZ,
  DEFAULT_RENDER_CHANNELS,
  DEFAULT_RENDER_WORKER_LIMIT,
  DEFAULT_PREVIEW_WINDOW_MS,
  MIN_PREVIEW_WINDOW_MS,
  MAX_PREVIEW_WINDOW_MS,
  DEFAULT_RENDER_EDGE_FADE_MS,
  MAX_RENDER_EDGE_FADE_MS,
  RENDER_DURATION_TOLERANCE_MS,
  RENDER_JOB_LIST_LIMIT_MAX,
  FFMPEG_STDERR_LIMIT_BYTES,
  FFMPEG_ARGV_SOFT_LIMIT,
  CROSSFADE_CURVE,
  RENDERER_VERSION,
  ANALYZER_NAME,
  ANALYZER_VERSION,
  DSP_ANALYZER_NAME,
  DSP_ANALYZER_VERSION,
  ANALYSIS_ENGINE_IDS,
  DEFAULT_ANALYSIS_ENGINE,
  ANALYSIS_SAMPLE_RATE_HZ,
  DNB_BPM_MIN,
  DNB_BPM_MAX,
  MAX_TEMPO_DEVIATION,
  MIN_ANALYSIS_CONFIDENCE,
  MIN_BPM_HINT_CONFIDENCE,
  PUBLISHED_BPM_INTEGER_TOLERANCE,
  PUBLISHED_BPM_FRACTION_TOLERANCE,
  DEFAULT_PHRASE_BARS,
  PHRASE_BAR_OPTIONS,
  DEFAULT_BASS_CROSSOVER_HZ,
  MIN_BASS_CROSSOVER_HZ,
  MAX_BASS_CROSSOVER_HZ,
  DEFAULT_BASS_SWAP_RAMP_MS,
  MIN_BASS_SWAP_RAMP_MS,
  MAX_BASS_SWAP_RAMP_MS,
  DEFAULT_BASS_LOW_ATTENUATION_DB,
  DEFAULT_MID_DIP_DB,
  BAND_HIGH_CROSSOVER_HZ,
  PHRASE_MIX_HIGHPASS_HZ,
  ANALYSIS_JOB_LIST_LIMIT_MAX,
} from "./constants.ts";
export { type AppConfig, appConfigSchema, type LogLevel, logLevelSchema, analysisEngineIdSchema } from "./config.ts";
export { loadConfig, type ConfigLoadOptions } from "./load-config.ts";
export { DomainError, type DomainErrorCode, isDomainError } from "./errors.ts";
export {
  camelotDistance,
  keyAgreement,
  normalizeKey,
  parseCamelot,
  type KeyAgreement,
  type NormalizedKey,
  type ParsedCamelot,
} from "./keys.ts";
export {
  assertPlaybackRate,
  barDurationMs,
  barIndexForBeat,
  beatPeriodMs,
  normalizeDnbBpm,
  publishedBpmTolerance,
  analyzerVersionLessThan,
  resolveBpmHint,
  phraseDurationMs,
  playbackRateForBpm,
  reconstructGrid,
  snapToNearestBeat,
  type NormalizedDnbBpm,
} from "./tempo.ts";
export const analysisScopeValues = ["ids", "planningReady", "unanalyzed", "stale", "all"] as const;
export type AnalysisScope = (typeof analysisScopeValues)[number];
export type {
  AnalysisJob,
  AnalysisJobStatus,
  AutomationEvent,
  AutomationTarget,
  BassSwapParams,
  BeatGrid,
  BeatGridSummary,
  MusicalKeyEstimate,
  SonicDescriptors,
  TempoEvidence,
  SuggestedCue,
  TrackAnalysis,
  TrackAnalysisView,
  TrackSection,
  TrackSectionType,
  TransitionProposal,
  TransitionValidation,
} from "./analysis.ts";
export {
  buildBeatGridSummary,
  clampBassSwapParams,
  resolveCanonicalBpm,
  resolveCanonicalKey,
} from "./analysis.ts";
export {
  clampMixPresetParams,
  defaultLowHandoverBar,
  expandPreset,
  isMonotoneBand,
  type MixPresetParams,
  type MixPresetType,
} from "./mix-presets.ts";
export {
  analysisJobSchema,
  analysisReportDataSchema,
  compareTrackAnalysesDataSchema,
  compareTrackAnalysesInputSchema,
  createCuePreviewDataSchema,
  createCuePreviewInputSchema,
  getAnalysisStatusInputSchema,
  getTrackAnalysisInputSchema,
  getTrackSectionsDataSchema,
  getTrackSectionsInputSchema,
  listAnalysisJobsDataSchema,
  listAnalysisJobsInputSchema,
  planTransitionDataSchema,
  planTransitionInputSchema,
  setBeatAnchorInputSchema,
  startTrackAnalysisInputSchema,
  analysisScopeSchema,
  trackAnalysisSchema,
  trackSectionSchema,
  transitionProposalSchema,
  validateTransitionDataSchema,
  validateTransitionInputSchema,
} from "./analysis-contracts.ts";
export { silentLogger, type Logger } from "./logger.ts";
export { fail, ok, type ToolErrorBody, type ToolResult } from "./tool-result.ts";
export { interpolateEnergy, scoreCandidate, hashSeed, type ScoreContext } from "./compatibility.ts";
export {
  type AnalysisEngineId,
  type AnalysisStatus,
  type BpmSource,
  type CuePoint,
  type CuePointType,
  type KeySource,
  type PublicTrack,
  type Track,
  type TrackMetadataPatch,
  toPublicTrack,
} from "./track.ts";
export type {
  CreateTransitionPreviewInput,
  ListRenderJobsResult,
  RenderJob,
  RenderJobKind,
  RenderJobStatus,
  RenderManifestTrack,
  RenderManifestV1,
  RenderOutputFormat,
  RenderReadiness,
  StartSetRenderInput,
} from "./render.ts";
export {
  cancelRenderJobDataSchema,
  cancelRenderJobInputSchema,
  createTransitionPreviewInputSchema,
  getRenderManifestInputSchema,
  getRenderStatusInputSchema,
  listRenderJobsDataSchema,
  listRenderJobsInputSchema,
  renderJobSchema,
  renderManifestV1Schema,
  renderReadinessSchema,
  startSetRenderInputSchema,
} from "./render-contracts.ts";
export type {
  CompatibleTrack,
  CreateSetPlanInput,
  CreateSetPlanResult,
  EnergyArcPoint,
  EnergyDiagnostic,
  EnergyDirection,
  PlanExplanation,
  PlanningReadiness,
  RejectionExplanation,
  ScoreBreakdown,
  ScoreComponents,
  SelectionExplanation,
  SetPlanEntry,
  SetPlanSummary,
  SetPlanV1,
  TransitionPlan,
  TransitionType,
  ValidateSetPlanResult,
  ValidationIssue,
} from "./planning.ts";
export {
  buildDnbSetPromptArgsSchema,
  createSetPlanDataSchema,
  createSetPlanInputSchema,
  cuePointSchema,
  deleteSetPlanDataSchema,
  deleteSetPlanInputSchema,
  emptyInputSchema,
  findCompatibleTracksDataSchema,
  findCompatibleTracksInputSchema,
  getPlanningReadinessInputSchema,
  getSetPlanInputSchema,
  getTrackDataSchema,
  getTrackInputSchema,
  libraryStatsDataSchema,
  listSetPlansDataSchema,
  listSetPlansInputSchema,
  planningReadinessDataSchema,
  publicTrackSchema,
  scanLibraryDataSchema,
  scanLibraryInputSchema,
  searchTracksDataSchema,
  searchTracksInputSchema,
  serverStatusDataSchema,
  setCuePointsDataSchema,
  setCuePointsInputSchema,
  setPlanV1Schema,
  toolErrorSchema,
  toolResultSchema,
  trackIdSchema,
  updateSetPlanInputSchema,
  updateTrackMetadataInputSchema,
  validateSetPlanDataSchema,
  validateSetPlanInputSchema,
  type LibraryStats,
  type ScanLibraryResult,
  type SearchTracksInput,
  type SearchTracksResult,
  type ServerStatus,
  type UpdateTrackMetadataInput,
} from "./contracts.ts";
