export { recordHourFeedbackSchema, listHourFeedbackSchema } from "./hour-feedback-contracts.ts";
export {
  APP_NAME,
  APP_VERSION,
  DEFAULT_SUPPORTED_EXTENSIONS,
  SEARCH_LIMIT_DEFAULT,
  SEARCH_LIMIT_MAX,
  RESOURCE_LIST_LIMIT,
  SCAN_WARNING_LIMIT,
  FINGERPRINT_WINDOW_BYTES,
  DEFAULT_TARGET_DURATION_MS,
  MIN_TARGET_DURATION_MS,
  MAX_TARGET_DURATION_MS,
  DEFAULT_TRANSITION_OVERLAP_MS,
  SHORT_CROSSFADE_MS,
  MIN_PLAYABLE_DURATION_MS,
  DURATION_TOLERANCE_MS,
  DURATION_QUALITY_WINDOW_MS,
  resolveTargetDurationMs,
  DEFAULT_ARTIST_REPEAT_SPACING,
  MAX_BPM_JUMP,
  MAX_CAMELOT_DISTANCE_OK,
  MAX_ENERGY_DEVIATION,
  SET_PLAN_LIST_LIMIT_MAX,
  COMPATIBLE_TRACKS_LIMIT_MAX,
  PLANNER_CANDIDATE_CAP,
  DEFAULT_SCORE_WEIGHTS,
  MIN_KEY_CONFIDENCE,
  PLANNER_POOL_MIN_TRACKS,
  PLANNER_POOL_RELAX_FACTOR,
  DEFAULT_LOUDNESS_TARGET_LUFS,
  DEFAULT_TRUE_PEAK_CEILING_DB,
  DEFAULT_RENDER_SAMPLE_RATE_HZ,
  DEFAULT_RENDER_OUTPUT_FORMAT,
  DEFAULT_RENDER_OUTPUT_EXTENSION,
  DEFAULT_RENDER_CHANNELS,
  DEFAULT_RENDER_WORKER_LIMIT,
  DEFAULT_PREVIEW_WINDOW_MS,
  MIN_PREVIEW_WINDOW_MS,
  MAX_PREVIEW_WINDOW_MS,
  DEFAULT_RENDER_EDGE_FADE_MS,
  MAX_RENDER_EDGE_FADE_MS,
  RENDER_DURATION_TOLERANCE_MS,
  RENDER_CHECK_RESIDUAL_FAIL_MS,
  RENDER_CHECK_AUDIO_CONFIDENT_MS,
  RENDER_CHECK_AUDIO_REVIEW_MS,
  RENDER_CHECK_LEVEL_STEP_FAIL_LU,
  LEVEL_MATCH_GAIN_MIN_DB,
  LEVEL_MATCH_GAIN_MAX_DB,
  RENDER_JOB_LIST_LIMIT_MAX,
  FFMPEG_STDERR_LIMIT_BYTES,
  FFMPEG_ARGV_SOFT_LIMIT,
  CROSSFADE_CURVE,
  RENDERER_VERSION,
  AUDIO_ENGINE_ID,
  DJ_HANDOFF_POLICY,
  DSP_ANALYZER_NAME,
  DSP_ANALYZER_VERSION,
  ANALYSIS_ENGINE_IDS,
  DEFAULT_ANALYSIS_ENGINE,
  ANALYSIS_SAMPLE_RATE_HZ,
  DNB_BPM_MIN,
  DNB_BPM_MAX,
  MAX_TEMPO_DEVIATION,
  ATEMPO_SKIP_THRESHOLD,
  ATEMPO_DRIFT_BUDGET_MS,
  MIN_ANALYSIS_CONFIDENCE,
  MIN_BPM_HINT_CONFIDENCE,
  PUBLISHED_BPM_INTEGER_TOLERANCE,
  PUBLISHED_BPM_FRACTION_TOLERANCE,
  DEFAULT_PHRASE_BARS,
  PHRASE_BAR_OPTIONS,
  normalizePhraseBars,
  type PhraseBarCount,
  DEFAULT_BASS_CROSSOVER_HZ,
  MIN_BASS_CROSSOVER_HZ,
  MAX_BASS_CROSSOVER_HZ,
  DEFAULT_BASS_SWAP_RAMP_MS,
  MIN_BASS_SWAP_RAMP_MS,
  MAX_BASS_SWAP_RAMP_MS,
  DEFAULT_BASS_LOW_ATTENUATION_DB,
  DEFAULT_MID_DIP_DB,
  BAND_HIGH_CROSSOVER_HZ,
  PHRASE_MIX_HIGHPASS_HZ,
  ANALYSIS_JOB_LIST_LIMIT_MAX,
} from "./constants.ts";
export {
  type AppConfig,
  appConfigSchema,
  type LogLevel,
  logLevelSchema,
  analysisEngineIdSchema,
} from "./config.ts";
export {
  hasDrumAndBassGenre,
  isDrumAndBassGenre,
  normalizeGenre,
  normalizeGenres,
} from "./genres.ts";
export {
  artistTokens,
  jaccard,
  normalizePersonName,
  recordingKeyFrom,
  remixTokens,
  stripFeaturing,
  titleTokens,
  yearFromDate,
} from "./identity.ts";
export {
  enrichmentJobSchema,
  enrichmentReportDataSchema,
  getEnrichmentReportInputSchema,
  getEnrichmentStatusInputSchema,
  listEnrichmentJobsDataSchema,
  startMetadataEnrichmentInputSchema,
  type EnrichmentJob,
  type EnrichmentReport,
  type EnrichmentScope,
} from "./enrichment-contracts.ts";
export { loadConfig, type ConfigLoadOptions } from "./load-config.ts";
export { DomainError, type DomainErrorCode, isDomainError } from "./errors.ts";
export {
  camelotDistance,
  camelotNumberDistance,
  harmonicClass,
  harmonicMixScore,
  harmonicRelation,
  isConfidentKeyClash,
  isConservativeHarmonic,
  keyAgreement,
  normalizeKey,
  parseCamelot,
  MIN_HARMONIC_CONFIDENCE,
  type HarmonicRelation,
  type KeyAgreement,
  type NormalizedKey,
  type ParsedCamelot,
} from "./keys.ts";
export {
  assertPlaybackRate,
  barDurationMs,
  barIndexForBeat,
  beatPeriodMs,
  foldedIntegerBpm,
  normalizeDnbBpm,
  pairTargetBpm,
  publishedBpmTolerance,
  resolvePublishedReferenceBpm,
  publishedReferenceCandidates,
  analyzerVersionLessThan,
  resolveBpmHint,
  phraseDurationMs,
  playbackRateForBpm,
  sourceBpmForRate,
  snapPlaybackRate,
  sourceToOutputMs,
  outputToSourceMs,
  playbackRateDriftMs,
  shouldSkipAtempo,
  effectivePlaybackRate,
  overlapOnlyPlayableMs,
  reconstructGrid,
  snapToNearestBeat,
  type NormalizedDnbBpm,
} from "./tempo.ts";
export const analysisScopeValues = ["ids", "planningReady", "unanalyzed", "stale", "all"] as const;
export type AnalysisScope = (typeof analysisScopeValues)[number];
export type {
  AnalysisJob,
  AnalysisJobStatus,
  AutomationEvent,
  AutomationTarget,
  BassSwapParams,
  BeatGrid,
  BeatGridSummary,
  MusicalKeyEstimate,
  SonicDescriptors,
  TempoEvidence,
  SuggestedCue,
  TrackAnalysis,
  TrackAnalysisView,
  TrackSection,
  TrackSectionType,
  TransitionProposal,
  TransitionValidation,
} from "./analysis.ts";
export {
  buildBeatGridSummary,
  clampBassSwapParams,
  resolveCanonicalBpm,
  resolveCanonicalKey,
  resolveCanonicalKeyConfidence,
} from "./analysis.ts";
export {
  chooseMixIntent,
  choosePhraseShape,
  resolveRenderPhraseShape,
  clampMixPresetParams,
  defaultLowHandoverBar,
  expandPreset,
  landingIncomingDropBar,
  isMonotoneBand,
  outgoingHoldBars,
  sequentialHandoffLabel,
  sectionAtMs,
  SEQUENTIAL_INCOMING_HEAD_ENERGY,
  SEQUENTIAL_OUTGOING_DROP_ENERGY,
  type MixIntent,
  type MixPresetParams,
  type MixPresetType,
  type PhraseShape,
} from "./mix-presets.ts";
export {
  analysisJobSchema,
  analysisReportDataSchema,
  compareTrackAnalysesDataSchema,
  compareTrackAnalysesInputSchema,
  createCuePreviewDataSchema,
  createCuePreviewInputSchema,
  getAnalysisStatusInputSchema,
  getTrackAnalysisInputSchema,
  getTrackSectionsDataSchema,
  getTrackSectionsInputSchema,
  listAnalysisJobsDataSchema,
  listAnalysisJobsInputSchema,
  planTransitionDataSchema,
  planTransitionInputSchema,
  setBeatAnchorInputSchema,
  startTrackAnalysisInputSchema,
  analysisScopeSchema,
  trackAnalysisSchema,
  trackSectionSchema,
  transitionProposalSchema,
  validateTransitionDataSchema,
  validateTransitionInputSchema,
} from "./analysis-contracts.ts";
export { silentLogger, type Logger } from "./logger.ts";
export { fail, ok, type ToolErrorBody, type ToolResult } from "./tool-result.ts";
export { interpolateEnergy, scoreCandidate, hashSeed, type ScoreContext } from "./compatibility.ts";
export {
  MOOD_PRESETS,
  moodPresetFor,
  resolveDescriptorFilters,
  type DescriptorFilters,
  type DescriptorPercentiles,
  type DescriptorRange,
} from "./mood-presets.ts";
export {
  continuousEnergy,
  descriptorValue,
  effectiveEnergy,
  genresMatchFilter,
  hasDescriptorFilters,
  matchesDescriptorFilters,
  moodPresetScore,
  valueInRange,
  type DescriptorValues,
} from "./descriptor-filters.ts";
export {
  type AnalysisEngineId,
  type AnalysisStatus,
  type BpmSource,
  type FieldSource,
  type CuePoint,
  type CuePointType,
  type KeySource,
  type PublicTrack,
  type Track,
  type TrackMetadataPatch,
  toPublicTrack,
} from "./track.ts";
export type {
  CreateTransitionPreviewInput,
  ListRenderJobsResult,
  RenderJob,
  RenderJobKind,
  RenderJobStatus,
  FrozenJoinEvidence,
  RenderManifestTrack,
  RenderManifestV1,
  RenderOutputFormat,
  RenderReadiness,
  StartSetRenderInput,
} from "./render.ts";
export {
  cancelRenderJobDataSchema,
  cancelRenderJobInputSchema,
  createTransitionPreviewInputSchema,
  getRenderManifestInputSchema,
  getRenderStatusInputSchema,
  listRenderJobsDataSchema,
  listRenderJobsInputSchema,
  renderJobSchema,
  renderManifestV1Schema,
  renderReadinessSchema,
  startSetRenderInputSchema,
} from "./render-contracts.ts";
export {
  LISTEN_RENDER_BIT_DEPTH,
  listenRenderFileName,
  listenRenderRelPath,
  slugifyRenderName,
} from "./render-listen.ts";
export type {
  CompatibleTrack,
  CreateSetPlanInput,
  CreateSetPlanResult,
  EnergyArcPoint,
  EnergyDiagnostic,
  EnergyDirection,
  JoinConstraintSatisfaction,
  JoinKeyEvidence,
  JoinQualityReport,
  JoinRecipeStatus,
  PlanExplanation,
  PlanQualityReport,
  PlanningConstraints,
  PlanningReadiness,
  QualityPolicy,
  RejectionExplanation,
  RequiredTransitionConstraint,
  RequiredTransitionReuse,
  RequiredTransitionStrength,
  ScoreBreakdown,
  ScoreComponents,
  SelectionExplanation,
  SelectionScoreBuckets,
  SetPlanEntry,
  SetPlanSummary,
  SetPlanV1,
  TransitionPlan,
  TransitionType,
  ValidateSetPlanResult,
  ValidationIssue,
} from "./planning.ts";
export {
  buildDnbSetPromptArgsSchema,
  createSetPlanDataSchema,
  createSetPlanInputSchema,
  cuePointSchema,
  deleteSetPlanDataSchema,
  deleteSetPlanInputSchema,
  emptyInputSchema,
  findCompatibleTracksDataSchema,
  findCompatibleTracksInputSchema,
  getPlanningReadinessInputSchema,
  getSetPlanInputSchema,
  getTrackDataSchema,
  getTrackInputSchema,
  libraryStatsDataSchema,
  listApprovedRecipesDataSchema,
  listApprovedRecipesInputSchema,
  listSetPlansDataSchema,
  listSetPlansInputSchema,
  planQualityReportSchema,
  planningReadinessDataSchema,
  publicTrackSchema,
  scanLibraryDataSchema,
  scanLibraryInputSchema,
  searchTracksDataSchema,
  searchTracksInputSchema,
  serverStatusDataSchema,
  setCuePointsDataSchema,
  setCuePointsInputSchema,
  setPlanV1Schema,
  toolErrorSchema,
  toolResultSchema,
  trackIdSchema,
  updateSetPlanInputSchema,
  updateTrackMetadataInputSchema,
  validateSetPlanDataSchema,
  validateSetPlanInputSchema,
  type LibraryStats,
  type ScanLibraryResult,
  type SearchTracksInput,
  type SearchTracksResult,
  type ServerStatus,
  type UpdateTrackMetadataInput,
} from "./contracts.ts";
export {
  recipeFingerprint,
  exactRecipeFingerprint,
  renderJoinFingerprint,
  renderSequenceFingerprint,
  canonicalRecipeJson,
  pairKey,
  type RecipeFingerprintInput,
} from "./recipe.ts";
export {
  resolveRateRegions,
  sourcePositionToOutputMs,
  outputPositionToSourceMs,
  resolvePlanRateRegionsVersion,
  type RateRegion,
  type RateRegionsResolution,
} from "./rate-regions.ts";
export {
  APPROVED_RECIPE_STATUSES,
  APPROVED_STATUS_RANK,
  approvedPairKey,
  pickApprovedRecipe,
  recipeApplicability,
  recipeFeasibility,
  reusableRecipeFingerprint,
  reusableRecipeFromJoin,
  type ApprovedRecipeRecord,
  type ApprovedRecipeStatus,
  type RecipeLiveIdentity,
  type RecipeFeasibility,
  type RecipeIdentitySnapshot,
  type ReusableRecipePayload,
  type SequentialHandoff,
} from "./approved-recipe.ts";
export {
  bpmDisagrees,
  downbeatPhaseAgreement,
  periodStats,
  type PeriodStats,
} from "./grid-metrics.ts";
export {
  FEEDBACK_DISLIKE_THRESHOLD,
  FEEDBACK_LIKE_THRESHOLD,
  isDislike,
  isLike,
  preferenceBonus,
  type FeedbackIndex,
  type FeedbackRatingValue,
  type RateTransitionInput,
  type TransitionFeedback,
  type TransitionPreference,
} from "./feedback.ts";
export {
  getTransitionPreferencesDataSchema,
  getTransitionPreferencesInputSchema,
  listTransitionFeedbackDataSchema,
  listTransitionFeedbackInputSchema,
  rateTransitionDataSchema,
  rateTransitionInputSchema,
  selectTrackEvidenceDataSchema,
  selectTrackEvidenceInputSchema,
  transitionFeedbackSchema,
  transitionPreferenceSchema,
} from "./feedback-contracts.ts";
